# constituents.py

NASDAQ100_TICKERS = [
    "AAPL", "MSFT", "AMZN", "NVDA", "GOOGL", "GOOG", "META", "TSLA", "AVGO", "COST",
    "ASML", "PEP", "TMUS", "CSCO", "ADBE", "TXN", "AMD", "QCOM", "NFLX", "AMGN",
    "INTU", "INTC", "CMCSA", "HON", "BKNG", "AMAT", "ISRG", "VRTX", "ADP", "SBUX",
    "MDLZ", "REGN", "GILD", "ADI", "PANW", "MU", "LRCX", "PDD", "KLAC", "SNPS",
    "CDNS", "MELI", "PYPL", "CRWD", "ORLY", "CSX", "MAR", "WDAY", "ROP", "ABNB",
    "NTES", "ROST", "CHTR", "CTAS", "MNST", "AEP", "DXCM", "IDXX", "MRVL", "ODFL",
    "KDP", "PAYX", "PCAR", "FTNT", "LULU", "AZN", "CPRT", "ON", "FAST", "VRSK",
    "EXC", "XEL", "CDW", "BKR", "BIIB", "CSGP", "GEHC", "FANG", "DLTR", "ANSS",
    "ROK", "WBD", "TTD", "MDB", "DDOG", "TEAM", "ALGN", "ILMN", "ZS", "EBAY",
    "ZM", "ENPH", "JD", "LCID"
]

SP500_TICKERS = [
    "AAPL", "MSFT", "AMZN", "NVDA", "GOOGL", "META", "BRK-B", "LLY", "AVGO", "JPM",
    "TSLA", "WMT", "V", "XOM", "UNH", "MA", "PG", "COST", "JNJ", "HD", "ORCL",
    "ABBV", "BAC", "KO", "NFLX", "MRK", "CVX", "CRM", "ADBE", "AMD", "PEP", "TMO",
    "WFC", "ACN", "CSCO", "MCD", "ABT", "GE", "INTU", "DHR", "TXN", "QCOM", "CAT"
]

NIFTY_50_TICKERS = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BPCL.NS",
    "BHARTIARTL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS",
    "DRREDDY.NS", "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS",
    "HDFCLIFE.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS",
    "ITC.NS", "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS",
    "LTIM.NS", "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS",
    "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SHRIRAMFIN.NS", "SBIN.NS",
    "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS"
]

NIFTY_NEXT50_TICKERS = [
    "ABB.NS", "AMBUJACEM.NS", "BANKBARODA.NS", "BERGEPAINT.NS", "BHARATFORG.NS",
    "BOSCHLTD.NS", "CANBK.NS", "CGPOWER.NS", "CHOLAFIN.NS", "COLPAL.NS",
    "DLF.NS", "DMART.NS", "GAIL.NS", "GODREJPROP.NS", "HAL.NS", "HAVELLS.NS",
    "ICICIGI.NS", "ICICIPRULI.NS", "IOC.NS", "IRCTC.NS", "IRFC.NS",
    "JINDALSTEL.NS", "JIOFIN.NS", "JSWENERGY.NS", "LICOFI.NS", "LODHA.NS",
    "MAXHEALTH.NS", "MOTHERSON.NS", "NAUKRI.NS", "NHPC.NS", "OIL.NS",
    "PAYTM.NS", "PFC.NS", "PNB.NS", "POLICYBZR.NS", "POONAWALLA.NS",
    "REC.NS", "RVNL.NS", "SIEMENS.NS", "SRF.NS", "SUPREMEIND.NS",
    "TATAPOWER.NS", "TRENT.NS", "TORNTPHARM.NS", "TVSMOTOR.NS", "MCDOWELL-N.NS",
    "VBL.NS", "VEDL.NS", "ZOMATO.NS", "ZYDUSLIFE.NS"
]

NIFTY_IT_TICKERS = [
    "TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS",
    "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS", "OFSS.NS"
]

NIFTY_BANK_TICKERS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS",
    "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS",
    "AUBANK.NS", "INDUSINDBK.NS"
]

NIFTY_FINSRV_TICKERS = [
    "AXISBANK.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "CHOLAFIN.NS", "HDFCBANK.NS",
    "HDFCLIFE.NS", "ICICIBANK.NS", "ICICIGI.NS", "ICICIPRULI.NS", "IDFCFIRSTB.NS",
    "JIOFIN.NS", "KOTAKBANK.NS", "LICHSGFIN.NS", "LICOFI.NS", "MUTHOOTFIN.NS",
    "PFC.NS", "REC.NS", "SBICARD.NS", "SBILIFE.NS", "SBIN.NS", "SHRIRAMFIN.NS"
]

NIFTY_MIDCAP100_TICKERS = [
    "3MINDIA.NS", "ABB.NS", "ACC.NS", "AAVAS.NS", "AARTIIND.NS", "ABBOTINDIA.NS",
    "ABCAPITAL.NS", "ABFRL.NS", "ADANIENSOL.NS", "ADANIPOWER.NS", "ALKYLAMINE.NS",
    "ALKEM.NS", "AMBUJACEM.NS", "APLLTD.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS",
    "ASTRAL.NS", "ATUL.NS", "AUBANK.NS", "AUROPHARMA.NS", "BALKRISIND.NS",
    "BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS", "BATAINDIA.NS", "BEL.NS",
    "BHARATFORG.NS", "BHEL.NS", "BIOCON.NS", "BIRLACORPN.NS", "BSOFT.NS",
    "CANBK.NS", "CANFINHOME.NS", "CGPOWER.NS", "CHAMBLFERT.NS", "CHOLAFIN.NS",
    "COFORGE.NS", "COLPAL.NS", "CONCOR.NS", "COROMANDEL.NS", "CROMPTON.NS",
    "CUMMINSIND.NS", "DALBHARAT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS", "DIXON.NS",
    "DLF.NS", "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS", "FORTIS.NS",
    "GAIL.NS", "GLAXO.NS", "GLENMARK.NS", "GODREJPROP.NS", "GUJGASLTD.NS",
    "HAVELLS.NS", "HDFCAMC.NS", "HINDPETRO.NS", "HONAUT.NS", "IDFCFIRSTB.NS",
    "INDIAMART.NS", "INDHOTEL.NS", "INDIANB.NS", "INDUSINDBK.NS", "INDUSTOWER.NS",
    "IPCALAB.NS", "IRCTC.NS", "IRFC.NS", "JUBLFOOD.NS", "KALYANKJIL.NS",
    "KEI.NS", "KPITTECH.NS", "L&TFH.NS", "LAURUSLABS.NS", "LICHSGFIN.NS",
    "LUPIN.NS", "MAXHEALTH.NS", "MFSL.NS", "MGL.NS", "MPHASIS.NS",
    "MRF.NS", "MUTHOOTFIN.NS", "NATIONALUM.NS", "NAVINFLUOR.NS", "NMDC.NS",
    "OBEROIRLTY.NS", "OFSS.NS", "OIL.NS", "PAGEIND.NS", "PERSISTENT.NS",
    "PETRONET.NS", "PFC.NS", "POLYCAB.NS", "PNB.NS", "POONAWALLA.NS",
    "RBLBANK.NS", "REC.NS", "SAIL.NS", "SHRIRAMFIN.NS", "SUZLON.NS",
    "TATACOMM.NS", "TATAELXSI.NS", "TATAPOWER.NS", "TIINDIA.NS", "TORNTPOWER.NS",
    "TRENT.NS", "TVSMOTOR.NS", "UBL.NS", "UPL.NS", "VBL.NS", "IDEA.NS",
    "VOLTAS.NS", "YESBANK.NS", "ZEEL.NS", "ZYDUSLIFE.NS"
]

NSE_500_TICKERS = [
    "3MINDIA.NS", "ABB.NS", "ACC.NS", "AAVAS.NS", "AARTIIND.NS", "AARTIDRUGS.NS",
    "AARTISURF.NS", "ABBOTINDIA.NS", "ABCAPITAL.NS", "ABFRL.NS", "ABSLAMC.NS",
    "ADANIENSOL.NS", "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS",
    "ATGL.NS", "AWL.NS", "AFFLE.NS", "AJANTPHARM.NS", "AKZOINDIA.NS", "ALKEM.NS",
    "ALKYLAMINE.NS", "ALLCARGO.NS", "ALOKINDS.NS", "AMBER.NS", "AMBUJACEM.NS",
    "ANGELONE.NS", "APARINDS.NS", "APLLTD.NS", "APOLLOHOSP.NS", "APOLLOTYRE.NS",
    "APTUS.NS", "ACI.NS", "ASAHIINDIA.NS", "ASHOKLEY.NS", "ASIANPAINT.NS",
    "ASTERDM.NS", "ASTRAL.NS", "ATUL.NS", "AUBANK.NS", "AUROPHARMA.NS", "AVANTIFEED.NS",
    "DMART.NS", "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJAJELEC.NS", "BAJAJFINSV.NS",
    "BAJFINANCE.NS", "BALAMINES.NS", "BALKRISIND.NS", "BALRAMCHIN.NS", "BANDHANBNK.NS",
    "BANKBARODA.NS", "BANKINDIA.NS", "MAHABANK.NS", "BATAINDIA.NS", "BAYERCROP.NS",
    "BDL.NS", "BEL.NS", "BEML.NS", "BERGEPAINT.NS", "BHARATFORG.NS", "BHEL.NS",
    "BHARTIARTL.NS", "BIOCON.NS", "BIRLACORPN.NS", "BSOFT.NS", "BLS.NS",
    "BLUESTARCO.NS", "BOSCHLTD.NS", "BPCL.NS", "BRIGADE.NS", "BRITANNIA.NS",
    "MAPMYINDIA.NS", "CESC.NS", "CGPOWER.NS", "CERA.NS", "CHAMBLFERT.NS",
    "CHOLAFIN.NS", "CHOLAHLDNG.NS", "CIPLA.NS", "CLEAN.NS", "COALINDIA.NS",
    "COCHINSHIP.NS", "COFORGE.NS", "COLPAL.NS", "CAMS.NS", "CONCOR.NS",
    "COROMANDEL.NS", "CRAFTSMAN.NS", "CREDITACC.NS", "CROMPTON.NS", "CSBBANK.NS",
    "CUMMINSIND.NS", "CYIENT.NS", "DALBHARAT.NS", "DATAPATTNS.NS", "DBCORP.NS",
    "DCBBANK.NS", "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS", "DELTACORP.NS",
    "DEVYANI.NS", "DIVISLAB.NS", "DIXON.NS", "DLF.NS", "DRREDDY.NS", "ECLERX.NS",
    "EICHERMOT.NS", "EIDPARRY.NS", "EIHOTEL.NS", "ELGIEQUIP.NS", "EMAMILTD.NS",
    "ENDURANCE.NS", "ENGINEERSIN.NS", "EPL.NS", "EQUITASBNK.NS", "ERIS.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS", "FACT.NS", "FINEORG.NS",
    "FINPIPE.NS", "FINCABLES.NS", "FSL.NS", "FIVESTAR.NS", "FORTIS.NS", "GAIL.NS",
    "GMRINFRA.NS", "GALAXYSURF.NS", "GICRE.NS", "GILLETTE.NS", "GLAND.NS",
    "GLAXO.NS", "GLENMARK.NS", "MEDANTA.NS", "GODREJAGRO.NS", "GODREJCP.NS",
    "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GRAPHITE.NS", "GRASIM.NS",
    "GESHIP.NS", "GRINDWELL.NS", "FLUOROCHEM.NS", "GUJGASLTD.NS", "GNFC.NS",
    "GPPL.NS", "GSFC.NS", "GSPL.NS", "HEG.NS", "HCLTECH.NS", "HDFCAMC.NS",
    "HDFCBANK.NS", "HDFCLIFE.NS", "HFCL.NS", "HAVELLS.NS", "HEROMOTOCO.NS",
    "HINDALCO.NS", "HINDCOPPER.NS", "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS",
    "HOMEFIRST.NS", "HONAUT.NS", "HUDCO.NS", "ICICIBANK.NS", "ICICIGI.NS",
    "ICICIPRULI.NS", "IDBI.NS", "IDFCFIRSTB.NS", "INDIACEM.NS", "INDIAMART.NS",
    "INDIANB.NS", "IEX.NS", "IOC.NS", "IOB.NS", "IRCTC.NS", "IRFC.NS",
    "INDIGOPNTS.NS", "IGL.NS", "INDHOTEL.NS", "INDUSINDBK.NS", "INDUSTOWER.NS",
    "INFIBEAM.NS", "NAUKRI.NS", "INFY.NS", "INOXWIND.NS", "INTELLECT.NS",
    "INDIGO.NS", "IPCALAB.NS", "JBCHEPHARM.NS", "JBMA.NS", "JKCEMENT.NS",
    "JKLAKSHMI.NS", "JKPAPER.NS", "JMFINANCIL.NS", "JSWENERGY.NS", "JSWINFRA.NS",
    "JSWSTEEL.NS", "JSL.NS", "JUBLFOOD.NS", "JUBLINGREA.NS", "JUBLPHARMA.NS",
    "JUSTDIAL.NS", "JYOTHYLAB.NS", "KALYANKJIL.NS", "KANSAINER.NS", "KARURVYSYA.NS",
    "KEC.NS", "KEI.NS", "KIOCL.NS", "KNRCON.NS", "KPITTECH.NS", "KPRMILL.NS",
    "KRBL.NS", "KSB.NS", "KOTAKBANK.NS", "L&TFH.NS", "LTTS.NS", "LICHSGFIN.NS",
    "LT.NS", "LATENTVIEW.NS", "LAURUSLABS.NS", "LXCHEM.NS", "LEMONTREE.NS",
    "LICOFI.NS", "LINDEINDIA.NS", "LODHA.NS", "LUPIN.NS", "MMTC.NS", "MOIL.NS",
    "MRF.NS", "MHRIL.NS", "MAHSEAMLES.NS", "M&MFIN.NS", "M&M.NS", "MANAPPURAM.NS",
    "MRPL.NS", "MARICO.NS", "MARUTI.NS", "MASTEK.NS", "MFSL.NS", "MAXHEALTH.NS",
    "MAZDOCK.NS", "MEDPLUS.NS", "METROPOLIS.NS", "MGL.NS", "MOTHERSON.NS",
    "MPHASIS.NS", "MCX.NS", "MUTHOOTFIN.NS", "NATCOPHARM.NS", "NATIONALUM.NS",
    "NAVINFLUOR.NS", "NAZARA.NS", "NBCC.NS", "NCC.NS", "NESTLEIND.NS",
    "NETWORK18.NS", "NHPC.NS", "NLCINDIA.NS", "NMDC.NS", "NOCIL.NS", "NTPC.NS",
    "NUVAMA.NS", "NYKAA.NS", "OBEROIRLTY.NS", "ONGC.NS", "OIL.NS", "OLECTRA.NS",
    "PAYTM.NS", "OFSS.NS", "ORIENTELEC.NS", "POLICYBZR.NS", "PCBL.NS", "PIIND.NS",
    "PNB.NS", "PNCINFRA.NS", "PVRINOX.NS", "PAGEIND.NS", "PATANJALI.NS",
    "PERSISTENT.NS", "PETRONET.NS", "PFC.NS", "PIDILITIND.NS", "PEL.NS",
    "PPLPHARMA.NS", "POLYCAB.NS", "POONAWALLA.NS", "POWERGRID.NS", "PRAJIND.NS",
    "PRESTIGE.NS", "PRINCEPIPE.NS", "PGHH.NS", "RAIN.NS", "RAJESHEXPO.NS",
    "RBLBANK.NS", "REC.NS", "RHIM.NS", "RITES.NS", "RCF.NS", "RELIANCE.NS",
    "RELIGARE.NS", "RBA.NS", "ROSSARI.NS", "ROUTE.NS", "SBICARD.NS", "SBILIFE.NS",
    "SJVN.NS", "SKFINDIA.NS", "SRF.NS", "SAFARI.NS", "MOTILALOFS.NS", "SANFI.NS",
    "SAPPHIRE.NS", "SAREGAMA.NS", "SCHAEFFLER.NS", "SHOPERSTOP.NS", "SHREE CEMENT.NS",
    "SHRIRAMFIN.NS", "SHYAMMETL.NS", "SIEMENS.NS", "SOBHA.NS", "SOLARINDS.NS",
    "SONACOMS.NS", "SONATSOFTW.NS", "STARHEALTH.NS", "SBIN.NS", "SAIL.NS",
    "SUMICHEM.NS", "SUNPHARMA.NS", "SUNTV.NS", "SUNDARMFIN.NS", "SUNDRMFAST.NS",
    "SUNTECK.NS", "SUPRAJIT.NS", "SUPREMEIND.NS", "SUVENPHAR.NS", "SUZLON.NS",
    "SYNGENE.NS", "SYRMA.NS", "TATACOMM.NS", "TATACONSUM.NS", "TATAELXSI.NS",
    "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TTECH.NS", "TTML.NS",
    "TCS.NS", "TECHM.NS", "TEJASNET.NS", "NIACL.NS", "RAMCOCEM.NS", "THERMAX.NS",
    "THYROCARE.NS", "TIINDIA.NS", "TIMKEN.NS", "TITAN.NS", "TORNTPHARM.NS",
    "TORNTPOWER.NS", "TRENT.NS", "TRIDENT.NS", "TRIVENI.NS", "TRITURBINE.NS",
    "TVSMOTOR.NS", "TV18BRDCST.NS", "UCOBANK.NS", "UNOMINDA.NS", "UPL.NS",
    "UTIAMC.NS", "UBL.NS", "MCDOWELL-N.NS", "VGUARD.NS", "VMART.NS", "VIPIND.NS",
    "VAIBHAVGBL.NS", "VBL.NS", "MANYAVAR.NS", "VEDL.NS", "VIJAYA.NS", "VINATIORGA.NS",
    "IDEA.NS", "VOLTAS.NS", "WELCORP.NS", "WELSPUNLIV.NS", "WESTLIFE.NS",
    "WHIRLPOOL.NS", "WIPRO.NS", "WOCKPHARMA.NS", "YESBANK.NS", "ZEEL.NS",
    "ZENSARTECH.NS", "ZOMATO.NS", "ZYDUSLIFE.NS", "KAYNES.NS", "CEINFO.NS"
]

RUSSELL_2000_TICKERS = [
    "SMCI", "CROX", "CELH", "ELF", "SFM", "ANF", "BOOT", "BLDR", "WING", "SKX",
    "INSM", "ONTO", "MOD", "FIX", "AGCO", "RBA", "GNTX", "MTH", "TOL", "TMHC",
    "KBH", "MHO", "SKWD", "GPI", "ABG", "LAD", "PAG", "ASB", "BOH", "CNO",
    "FHN", "FNB", "HWC", "ONB", "OZK", "PB", "PNFP", "SNV", "UMBF", "VLY",
    "WAL", "WTFC", "WBS", "ZION", "AAL", "ALGT", "ATSG", "CAR", "CHRW", "HUBG",
    "JBHT", "KNX", "MATX", "R", "SAIA", "WERN", "XPO", "HALO", "HQY", "LNTH",
    "MEDP", "MMS", "NEOG", "NTRA", "OSUR", "PEN", "RCM", "SILK", "SRDX", "TNDM",
    "UTHR", "CERT", "DOCS", "EXEL", "GKOS", "ICUI", "IRTC", "MASI", "MYGN", "NEO",
    "NVCR", "PODD", "QDEL", "TXG", "RGEN", "ALRM", "APPF", "AYX", "BAND", "BL",
    "CALX", "CCCS", "CSGP", "DOCN", "DOMO", "ENV", "FSLY", "GTLB", "JAMF", "LAW",
    "LPSN", "MAPS", "MSTR", "NABL", "NCNO", "NET", "NTNX", "PAY", "PD", "PING",
    "PLTR", "PRO", "PSTG", "QTWO", "RPD", "S", "SPSC", "SPT", "SSNC", "TENB",
    "TNGR", "U", "WK", "YEXT", "ZI"
]
